/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bab7;

/**
 *
 * @author ADMIN
 */
public class FormBerita extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormBerita.class.getName());

    /**
     * Creates new form FormBerita
     */
    public FormBerita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtJurnalis = new javax.swing.JTextField();
        txtJudul = new javax.swing.JTextField();
        txtInfoKhusus = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        cmbJenis = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBerita = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnCekCasting = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        cmbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Berita Turnamen", "Berita Transfer" }));

        jLabel1.setText("Judul Berita");

        jLabel2.setText("Jurnalis");

        jLabel3.setText("Nama Turnamen / Pro-Player");

        jLabel4.setText("BERITA E-SPORT TERKINI");

        tblBerita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jenis Berita", "Judul Berita", "Jurnalis", "Nama Turnamen / Pro-Player"
            }
        ));
        jScrollPane3.setViewportView(tblBerita);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnBatal.setText("Batal");
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        btnClose.setText("Close");
        btnClose.addActionListener(this::btnCloseActionPerformed);

        btnCekCasting.setText("Casting");
        btnCekCasting.addActionListener(this::btnCekCastingActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatal)
                        .addGap(18, 18, 18)
                        .addComponent(btnClose)
                        .addGap(18, 18, 18)
                        .addComponent(btnCekCasting)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(209, 209, 209))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbJenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtInfoKhusus)
                            .addComponent(txtJurnalis)
                            .addComponent(txtJudul)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJurnalis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInfoKhusus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnHapus)
                    .addComponent(btnBatal)
                    .addComponent(btnClose)
                    .addComponent(btnCekCasting))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
      // IMPLEMENTASI EXCEPTION HANDLING
        try {
            String judul = txtJudul.getText();
            String jurnalis = txtJurnalis.getText();
            String infoKhusus = txtInfoKhusus.getText(); 
            
            // Mencegah NullPointerException jika dropdown bermasalah
            if (cmbJenis.getSelectedItem() == null) {
                throw new NullPointerException("Pilihan jenis berita tidak terbaca!");
            }
            String jenisTerpilih = cmbJenis.getSelectedItem().toString();

            // Melempar Exception buatan (IllegalArgumentException) jika ada form yang kosong
            if (judul.isEmpty() || jurnalis.isEmpty() || infoKhusus.isEmpty()) {
                throw new IllegalArgumentException("Data belum lengkap, mohon isi semua kolom!");
            }

            // --- PROSES MENYIMPAN KE TABEL (Tetap menggunakan Polimorfisme) ---
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblBerita.getModel();
            Berita berita; 

            if (jenisTerpilih.equals("Berita Turnamen")) {
                berita = new BeritaTurnamen(); 
            } else {
                berita = new BeritaTransfer(); 
            }
            
            berita.setBerita("-", judul, infoKhusus); 
            model.addRow(new Object[]{berita.getJenisBerita(), berita.judul, jurnalis, berita.game});
            
            // Membersihkan form otomatis
            txtJudul.setText("");
            txtJurnalis.setText("");
            txtInfoKhusus.setText("");
            cmbJenis.setSelectedIndex(0);
            txtJudul.requestFocus();

        } catch (IllegalArgumentException e) {
            // POP-UP EXCEPTION 1: Menangkap error form kosong
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Peringatan Input", javax.swing.JOptionPane.WARNING_MESSAGE);
            
        } catch (Exception e) {
            // POP-UP EXCEPTION 2: Menangkap error sistem lainnya yang tidak terduga
            javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan sistem: " + e.getMessage(), "Error Kesalahan", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // Mengambil model dari tabel
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblBerita.getModel();
        
        // Mendapatkan index baris yang di-klik user
        int barisTerpilih = tblBerita.getSelectedRow();

        if (barisTerpilih >= 0) {
            // Hapus baris jika ada yang dipilih
            model.removeRow(barisTerpilih);
        } else {
            // Tampilkan pesan error jika user belum memilih baris
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih baris di tabel yang ingin dihapus terlebih dahulu.");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        txtJudul.setText("");
        txtJurnalis.setText("");
        txtInfoKhusus.setText("");
        cmbJenis.setSelectedIndex(0); // Kembali ke pilihan pertama
        txtJudul.requestFocus(); // Kursor kembali berkedip di kolom Judul
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0); // Perintah untuk mematikan program Java
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnCekCastingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekCastingActionPerformed
        int barisTerpilih = tblBerita.getSelectedRow();
        
        if (barisTerpilih < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih salah satu baris data pada tabel terlebih dahulu!");
            return;
        }
        
        // Mengambil data dari tabel
        String jenis = tblBerita.getValueAt(barisTerpilih, 0).toString();
        String judul = tblBerita.getValueAt(barisTerpilih, 1).toString();
        String game = tblBerita.getValueAt(barisTerpilih, 3).toString();
        
        // 1. IMPLEMENTASI UPCASTING
        // Objek dari kelas anak (BeritaTurnamen/BeritaTransfer) dimasukkan ke variabel kelas induk (Berita)
        Berita beritaInduk;
        
        if (jenis.equals("Hasil Turnamen")) {
            beritaInduk = new BeritaTurnamen(); // Upcasting otomatis
        } else {
            beritaInduk = new BeritaTransfer(); // Upcasting otomatis
        }
        
        beritaInduk.setBerita("-", judul, game);
        
        // 2. IMPLEMENTASI DOWNCASTING & INSTANCEOF
        // Mengecek tipe objek asli dan melakukan casting kembali ke kelas anak secara eksplisit
        if (beritaInduk instanceof BeritaTurnamen) {
            BeritaTurnamen bTurnamen = (BeritaTurnamen) beritaInduk; // DOWNCASTING eksplisit
            
            // Mengakses method spesifik milik kelas anak setelah downcasting
            String pesanSpesifik = bTurnamen.dapatkanBonusJuara();
            javax.swing.JOptionPane.showMessageDialog(this, "Berita Terseleksi: " + bTurnamen.judul + "\n" + pesanSpesifik);
            
        } else if (beritaInduk instanceof BeritaTransfer) {
            BeritaTransfer bTransfer = (BeritaTransfer) beritaInduk; // DOWNCASTING eksplisit
            
            // Mengakses method spesifik milik kelas anak setelah downcasting
            String pesanSpesifik = bTransfer.dapatkanDetailKontrak();
            javax.swing.JOptionPane.showMessageDialog(this, "Berita Terseleksi: " + bTransfer.judul + "\n" + pesanSpesifik);
        }
    }//GEN-LAST:event_btnCekCastingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormBerita().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCekCasting;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblBerita;
    private javax.swing.JTextField txtInfoKhusus;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtJurnalis;
    // End of variables declaration//GEN-END:variables
}
